FROM ubuntu:22.04

WORKDIR /ws

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
    python3-pip

RUN pip3 install clang-format==15.0.7

ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o Kulki
RUN useradd -m -u $UID -g $GID -o -s /bin/bash Kulki

USER Kulki

ADD .clang-format /ws/
