name: ClangFormat

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build clang-format image
      run: docker build -t kulki_cf -f docker/Dockerfile.format .

    - name: Check clang-format style
      run: |
        docker run -it --rm -v"$(pwd):/Kulki:ro" kulki_cf:latest sh -c "find /Kulki -iname "*.hpp" -o -iname "*.cpp" | xargs clang-format -dry-run --Werror"

