name: GCC

on:
  push:
    branches:  
      - '**' 
  pull_request:
    branches:
       - '**' 

jobs:
  build:

    runs-on: ubuntu-22.04
    env:
      CC: gcc
      CXX: g++

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt -y install g++ gcc libsfml-dev

    - name: FetchSubmodules
      run: |
        git submodule init
        git submodule update

    - name: Build GCC
      run: |
        mkdir -p build
        cd build
        cmake ../
        cmake --build . -j
