name: GCC

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: |
        git submodule init
        git submodule update

    - name: gcc
      run: docker build . --file docker/Dockerfile.gcc --tag kulki_docker_gcc:$(date +%s)
